"""empty message

Revision ID: 7a43a88d50d9
Revises: e8ec7da81a94
Create Date: 2024-09-13 21:46:01.952026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a43a88d50d9'
down_revision = 'e8ec7da81a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('saved_filename')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('saved_filename', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
